mysql: &mysql
  adapter: mysql2
  database: "<%=ENV['OPENSHIFT_APP_NAME']%>"
  username: "<%=ENV['OPENSHIFT_MYSQL_DB_USERNAME']%>"
  password: "<%=ENV['OPENSHIFT_MYSQL_DB_PASSWORD']%>"
  host:     <%=ENV['OPENSHIFT_MYSQL_DB_HOST']%>
  port:     <%=ENV['OPENSHIFT_MYSQL_DB_PORT']%>


defaults: &defaults
  pool: 5
  timeout: 5000
  encoding: utf8
  <<: *<%= ENV['RAILS_DB'] || "mysql" %>

development:
    pool: 5
    timeout: 5000
    encoding: utf8
    adapter: mysql2
    database: finaltest
    username: root
    password: nikolas89
    host: localhost
    port: 3000

test: &test
  <<: *defaults

production:
  <<: *defaults
